"""常量定义"""

# ==================== 默认切块参数 ====================
DOCUMENT_CHUNK_SIZE = 600
DOCUMENT_CHUNK_OVERLAP = 100

# Parent-Child RAG 切块参数：Child 做检索，Parent 给大模型阅读。
DOCUMENT_PARENT_CHUNK_SIZE = 500
DOCUMENT_PARENT_CHUNK_OVERLAP = 60
DOCUMENT_CHILD_CHUNK_SIZE = 150
DOCUMENT_CHILD_CHUNK_OVERLAP = 30

# 文章类文档切块参数
DOCUMENT_ARTICLE_CHUNK_SIZE = 280
DOCUMENT_ARTICLE_CHUNK_OVERLAP = 50

# 对话历史切块规则
CHAT_CHUNK_SIZE = 500
CHAT_CHUNK_OVERLAP = 80
